---
suseconnect-d: ["basic12sp5", "basic12sp4", "basic15sp7", "basic15sp6", "basic15sp5", "basic15sp4", "basic15sp3", "basic15sp2", "basic15sp1", "basicmicro5", "basicmicro6", "basic16v0"]
labname: "basic"
requiredsecrets: ["sleregcode", "microregcode"]
requiredplugins: ["vagrant-libvirt", "vagrant-reload"]
