---
suseconnect-d: ["hana15_saphanasr-angi_performance_iscsi", "hana15_saphanasr-angi_cost_iscsi", "hana15_saphanasr_performance_iscsi", "hana15_saphanasr_cost_iscsi", "hana15_saphanasr-angi_performance_n1", "hana15_saphanasr-angi_cost_n1", "hana15_saphanasr_performance_n1", "hana15_saphanasr_cost_n1", "hana15_saphanasr-angi_performance_n2", "hana15_saphanasr-angi_cost_n2", "hana15_saphanasr_performance_n2", "hana15_saphanasr_cost_n2", "hana15trento"]
labname: "hana15"
requiredsecrets: ["sleregcode", "sapregcode"]
requiredplugins: ["vagrant-libvirt"]
floatingip1_saphanasr-angi_performance: ".43"
floatingip1_saphanasr-angi_cost: ".53"
floatingip1_saphanasr_performance: ".63"
floatingip1_saphanasr_cost: ".73"
ra: "SAPHanaSR-angi"
optimized: "performance"
