box: "sle12sp5"
short: "major-up"
fqdn: "major-up.labs.suse.com"
subnet: "primarysubnet"
ipaddress: ".15"
cpus: "1"
memory: "1024"
provisioning: "client/bootstrap.sh"
files: "client/files"
environment: "SLE12"
static: "N"
