---
box:
  sle15sp5: "SLES-15-SP5-Vagrant.x86_64"
  sle15sp4: "SLES-15-SP4-Vagrant.x86_64"
  sle15sp3: "SLES-15-SP3-Vagrant.x86_64"
  sle15sp2: "SLES-15-SP2-Vagrant.x86_64"
  sle15sp1: "SLES-15-SP1-Vagrant.x86_64"
  sle12sp5: "SLES-12-SP5-Vagrant.x86_64"
  sle12sp4: "SLES-12-SP4-Vagrant.x86_64"
  sle12sp3: "SLES-12-SP3-Vagrant.x86_64"
  sle12sp2: "SLES-12-SP2-Vagrant.x86_64"
  sle12sp1: "SLES-12-SP1-Vagrant.x86_64"
  windows2019: "peru/windows-server-2019-standard-x64-eval"
  rhel8: "generic/rhel8"
boxurl:
  sle15sp5: "http://download.opensuse.org/repositories/Virtualization:/Appliances:/Images:/SLE-15-SP5/images/boxes/SLES-15-SP5-Vagrant.x86_64.json"
  sle15sp4: "http://download.opensuse.org/repositories/Virtualization:/Appliances:/Images:/SLE-15-SP4/images/boxes/SLES-15-SP4-Vagrant.x86_64.json"
  sle15sp3: "http://download.opensuse.org/repositories/Virtualization:/Appliances:/Images:/SLE-15-SP3/images/boxes/SLES-15-SP3-Vagrant.x86_64.json"
  sle15sp2: "http://download.opensuse.org/repositories/Virtualization:/Appliances:/Images:/SLE-15-SP2/images/boxes/SLES-15-SP2-Vagrant.x86_64.json"
  sle15sp1: "http://download.opensuse.org/repositories/Virtualization:/Appliances:/Images:/SLE-15-SP1/images/boxes/SLES-15-SP1-Vagrant.x86_64.json"
  sle12sp5: "http://download.opensuse.org/repositories/Virtualization:/Appliances:/Images:/SLE-12-SP5/images/boxes/SLES-12-SP5-Vagrant.x86_64.json"
  sle12sp4: "http://download.opensuse.org/repositories/Virtualization:/Appliances:/Images:/SLE-12-SP4/images/boxes/SLES-12-SP4-Vagrant.x86_64.json"
  sle12sp3: "http://download.opensuse.org/repositories/Virtualization:/Appliances:/Images:/SLE-12-SP3/images/boxes/SLES-12-SP3-Vagrant.x86_64.json"
  sle12sp2: "http://download.opensuse.org/repositories/Virtualization:/Appliances:/Images:/SLE-12-SP2/images/boxes/SLES-12-SP2-Vagrant.x86_64.json"
  sle12sp1: "http://download.opensuse.org/repositories/Virtualization:/Appliances:/Images:/SLE-12-SP1/images/boxes/SLES-12-SP1-Vagrant.x86_64.json"
