---
box:
  sle15sp5: "SLES15-SP5-Vagrant.x86_64"
  sle15sp4: "SLES-15-SP4-Vagrant.x86_64"
  sle15sp3: "SLES-15-SP3-Vagrant.x86_64"
  sle15sp2: "SLES-15-SP2-Vagrant.x86_64"
  sle15sp1: "SLES-15-SP1-Vagrant.x86_64"
  sle12sp5: "SLES-12-SP5-Vagrant.x86_64"
  sle12sp4: "SLES-12-SP4-Vagrant.x86_64"
  sle12sp3: "SLES-12-SP3-Vagrant.x86_64"
  sle12sp2: "SLES-12-SP2-Vagrant.x86_64"
  sle12sp1: "SLES-12-SP1-Vagrant.x86_64"
  leap15sp4: "opensuse/Leap-15.4.x86_64"
  leap42sp3: "generic/opensuse42"
  windows2019: "peru/windows-server-2019-standard-x64-eval"
  rhel7: "generic/rhel7"
  rhel8: "generic/rhel8"
  rhel9: "generic/rhel9"
  oel6: "generic/oracle6"
  oel7: "generic/oracle7"
  oel8: "generic/oracle8"
  oel9: "generic/oracle9"
  alma8: "generic/alma8"
  alma9: "generic/alma9"
  amazon2: "bento/amazonlinux-2"
  centos7: "generic/centos7"
  centos8: "generic/centos8"
  debian10: "generic/debian10"
  debian11: "generic/debian11"
  rocky8: "generic/rocky8"
  rocky9: "generic/rocky9"
  ubuntu1804: "generic/ubuntu1804"
  ubuntu2004: "generic/ubuntu2004"
  ubuntu2204: "generic/ubuntu2204"
boxurl:
  sle15sp5: "http://download.opensuse.org/repositories/Virtualization:/Appliances:/Images:/SLE-15-SP5/images/boxes/SLES15-SP5-Vagrant.x86_64.json"
  sle15sp4: "http://download.opensuse.org/repositories/Virtualization:/Appliances:/Images:/SLE-15-SP4/images/boxes/SLES-15-SP4-Vagrant.x86_64.json"
  sle15sp3: "http://download.opensuse.org/repositories/Virtualization:/Appliances:/Images:/SLE-15-SP3/images/boxes/SLES-15-SP3-Vagrant.x86_64.json"
  sle15sp2: "http://download.opensuse.org/repositories/Virtualization:/Appliances:/Images:/SLE-15-SP2/images/boxes/SLES-15-SP2-Vagrant.x86_64.json"
  sle15sp1: "http://download.opensuse.org/repositories/Virtualization:/Appliances:/Images:/SLE-15-SP1/images/boxes/SLES-15-SP1-Vagrant.x86_64.json"
  sle12sp5: "http://download.opensuse.org/repositories/Virtualization:/Appliances:/Images:/SLE-12-SP5/images/boxes/SLES-12-SP5-Vagrant.x86_64.json"
  sle12sp4: "http://download.opensuse.org/repositories/Virtualization:/Appliances:/Images:/SLE-12-SP4/images/boxes/SLES-12-SP4-Vagrant.x86_64.json"
  sle12sp3: "http://download.opensuse.org/repositories/Virtualization:/Appliances:/Images:/SLE-12-SP3/images/boxes/SLES-12-SP3-Vagrant.x86_64.json"
  sle12sp2: "http://download.opensuse.org/repositories/Virtualization:/Appliances:/Images:/SLE-12-SP2/images/boxes/SLES-12-SP2-Vagrant.x86_64.json"
  sle12sp1: "http://download.opensuse.org/repositories/Virtualization:/Appliances:/Images:/SLE-12-SP1/images/boxes/SLES-12-SP1-Vagrant.x86_64.json"
