# The purpose of this file is to provide confidential variables, such as registration codes. 
# Note that the GitHub project does not sync this file.
# Copy this file as secret.yaml, and configure below. The file can be placed in the root project directory or the same directory as secret_example.yaml. The root project directory secret.yaml will take precedence, if it exists.

# Registration code for base SLES
sleregcode: ""
# Registration code for base SLE Micro
microregcode: ""
# Registration code for High Availability Extension 
haregcode: ""
# Registration code for SLES for SAP
sapregcode: ""
# Registration code for SUSE Manager
sumaregcode: ""
# Registration code for SUSE Manager Proxy
sumaproxyregcode: ""
# Registration code for SLE Live Patching
livepatchregcode: ""   
# SCC Org Mirroring credential Username
sccorguser: ""
# SCC Org Mirroring credential Password
sccorgpass: ""   


# Used by suma lab. TODO: Move to lab specific secret.yaml file
sccemptyuser: ""
sccemptypass: ""
